### ISSUE TITLE
Size is too large on Android tablet

### ISSUE THREAD

**Issue by barnabaslabs** [claypotfrog/GNTSP#1]
![Screenshot_20240228-074358](https://github.com/claypotfrog/GNTSP/assets/121033/aad53b3e-669b-4dc3-b9f3-a37d27d82c7b)
![Screenshot_20240228-073721](https://github.com/claypotfrog/GNTSP/assets/121033/712640a4-aa13-41d4-8610-37454c28036b)

**Comment by claypotfrog** [comment]
Thank you so much for reporting this WITH images.  Can you please tell me
what kind of tablet you are using?  I test the builds on an Android
emulator, and I didn't see this issue on either the generic 7" or 10"
tablets.  So clearly I'm missing someone in my testing.

Thank you.

Jeff

**Comment by barnabaslabs** [comment]
Thanks for you work on this Jeff! I might be an edge case since I am using a BOOX Note Air3c https://shop.boox.com/products/noteair3

I also have a Samsung Galaxy tab that I will test it on. 

While I am being needy, I would love to have a dark mode!

**Comment by claypotfrog** [comment]
Fixed in version 2.2 which resizes rather than scales the items on the screen.

**Comment by barnabaslabs** [comment]
Thanks for this! I can confirm the size is appropriate for my tablet now!

**Comment by claypotfrog** [comment]
I'm so glad.  Thank you for letting me know.  WHen I closed the buy, I
meant to write you and ask if it's working properly on your tablet.  I
tested it on all the tablets in Android studio, and it worked properly on
them.  But that's still a fairly limited sample size. :-)

Jeff
